--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5




--
-- Name: aceite_termo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aceite_termo (
    id bigint NOT NULL,
    aceite_autoria boolean NOT NULL,
    aceite_banca boolean NOT NULL,
    aceite_exibicao boolean NOT NULL,
    aceite_termo_completo boolean NOT NULL,
    aceite_titularidade boolean NOT NULL,
    data_aceite timestamp(6) without time zone,
    ip_address character varying(255),
    user_agent character varying(255),
    versao_termo character varying(255) NOT NULL,
    autora_id bigint NOT NULL,
    submissao_id bigint NOT NULL
);



--
-- Name: aceite_termo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.aceite_termo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aceite_termo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: autora; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.autora (
    id bigint NOT NULL,
    biografia character varying(2000),
    nome character varying(255) NOT NULL,
    email character varying(255),
    redes_sociais character varying(255),
    usuario_id bigint
);

--
-- Name: autora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.autora ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.autora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: competicao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.competicao (
    id bigint NOT NULL,
    fase_atual character varying(255),
    status_fase character varying(255),
    CONSTRAINT competicao_fase_atual_check CHECK (((fase_atual)::text = ANY ((ARRAY['FASE_32'::character varying, 'OITAVAS'::character varying, 'QUARTAS'::character varying, 'SEMIFINAL'::character varying, 'FINAL'::character varying, 'CAMPEA'::character varying])::text[]))),
    CONSTRAINT competicao_status_fase_check CHECK (((status_fase)::text = ANY ((ARRAY['NAO_INICIADA'::character varying, 'EM_ANDAMENTO'::character varying, 'ENCERRADA'::character varying])::text[])))
);



--
-- Name: competicao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.competicao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.competicao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: confronto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.confronto (
    id bigint NOT NULL,
    fase character varying(255),
    resolvido boolean,
    submissao_casa_id bigint,
    submissao_fora_id bigint,
    submissao_vencedora_id bigint,
    CONSTRAINT confronto_fase_check CHECK (((fase)::text = ANY ((ARRAY['FASE_32'::character varying, 'OITAVAS'::character varying, 'QUARTAS'::character varying, 'SEMIFINAL'::character varying, 'FINAL'::character varying, 'CAMPEA'::character varying])::text[])))
);



--
-- Name: confronto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.confronto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.confronto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evento (
    id bigint NOT NULL,
    ativo boolean,
    data_fim date,
    data_inicio date,
    nome character varying(255) NOT NULL,
    tema character varying(255)
);



--
-- Name: evento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grupo_competicao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grupo_competicao (
    id bigint NOT NULL,
    fase character varying(255) NOT NULL,
    nome_grupo character varying(255) NOT NULL,
    banca_id bigint,
    CONSTRAINT grupo_competicao_fase_check CHECK (((fase)::text = ANY ((ARRAY['FASE_32'::character varying, 'OITAVAS'::character varying, 'QUARTAS'::character varying, 'SEMIFINAL'::character varying, 'FINAL'::character varying])::text[]))),
    CONSTRAINT grupo_competicao_nome_grupo_check CHECK (((nome_grupo)::text = ANY ((ARRAY['A'::character varying, 'B'::character varying, 'C'::character varying, 'D'::character varying, 'E'::character varying, 'F'::character varying, 'G'::character varying, 'H'::character varying])::text[])))
);



--
-- Name: grupo_competicao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.grupo_competicao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupo_competicao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submissao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.submissao (
    id bigint NOT NULL,
    arquivo_completo_url character varying(255),
    arquivo_publico_url character varying(255),
    categoria character varying(255),
    data_submissao timestamp without time zone NOT NULL,
    descricao character varying(2000),
    status character varying(255),
    tipo_exibicao character varying(255),
    titulo character varying(255) NOT NULL,
    autora_id bigint,
    evento_id bigint,
    fase_atual character varying(255),
    grupo_id bigint,

    CONSTRAINT submissao_fase_atual_check CHECK (((fase_atual)::text = ANY ((ARRAY['FASE_32'::character varying, 'OITAVAS'::character varying, 'QUARTAS'::character varying, 'SEMIFINAL'::character varying, 'FINAL'::character varying, 'CAMPEA'::character varying])::text[]))),
    CONSTRAINT submissao_status_check CHECK (((status)::text = ANY ((ARRAY['SUBMETIDA'::character varying, 'NAO_SELECIONADA'::character varying, 'EM_COMPETICAO'::character varying, 'CLASSIFICADA'::character varying, 'ELIMINADA'::character varying, 'CAMPEA'::character varying])::text[]))),
    CONSTRAINT submissao_tipo_exibicao_check CHECK (((tipo_exibicao)::text = ANY ((ARRAY['TRECHO'::character varying, 'COMPLETO'::character varying])::text[])))
);



--
-- Name: submissao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.submissao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    senha character varying(255) NOT NULL,
    CONSTRAINT usuario_role_check CHECK (((role)::text = ANY ((ARRAY['AUTORA'::character varying, 'BANCA'::character varying, 'ADMIN'::character varying])::text[])))
);



--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voto_final; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.voto_final (
    id bigint NOT NULL,
    data_voto timestamp(6) without time zone NOT NULL,
    banca_id bigint NOT NULL,
    submissao_id bigint NOT NULL
);



--
-- Name: voto_final_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.voto_final ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voto_final_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aceite_termo aceite_termo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aceite_termo
    ADD CONSTRAINT aceite_termo_pkey PRIMARY KEY (id);


--
-- Name: autora autora_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.autora
    ADD CONSTRAINT autora_pkey PRIMARY KEY (id);


--
-- Name: competicao competicao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.competicao
    ADD CONSTRAINT competicao_pkey PRIMARY KEY (id);


--
-- Name: confronto confronto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.confronto
    ADD CONSTRAINT confronto_pkey PRIMARY KEY (id);


--
-- Name: evento evento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evento
    ADD CONSTRAINT evento_pkey PRIMARY KEY (id);


--
-- Name: grupo_competicao grupo_competicao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grupo_competicao
    ADD CONSTRAINT grupo_competicao_pkey PRIMARY KEY (id);


--
-- Name: submissao submissao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissao
    ADD CONSTRAINT submissao_pkey PRIMARY KEY (id);


--
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);




--
-- Name: aceite_termo ukbfhe5vekwmm32qsguqencydgn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aceite_termo
    ADD CONSTRAINT ukbfhe5vekwmm32qsguqencydgn UNIQUE (submissao_id);


--
-- Name: autora ukngxwen8w3o09iwre9223r29ta; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.autora
    ADD CONSTRAINT ukngxwen8w3o09iwre9223r29ta UNIQUE (usuario_id);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: voto_final voto_final_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voto_final
    ADD CONSTRAINT voto_final_pkey PRIMARY KEY (id);


--
-- Name: aceite_termo fk19da3q5ekbwc5th1snnfvc7gd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aceite_termo
    ADD CONSTRAINT fk19da3q5ekbwc5th1snnfvc7gd FOREIGN KEY (autora_id) REFERENCES public.autora(id);


--
-- Name: submissao fk4twqku1x6qpqlxwu3ps280v8p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissao
    ADD CONSTRAINT fk4twqku1x6qpqlxwu3ps280v8p FOREIGN KEY (autora_id) REFERENCES public.autora(id);


--
-- Name: confronto fk5hbaorsa2byt0dqh7v53yqeqd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.confronto
    ADD CONSTRAINT fk5hbaorsa2byt0dqh7v53yqeqd FOREIGN KEY (submissao_vencedora_id) REFERENCES public.submissao(id);


--
-- Name: submissao fk5u07riui9bg3m4ej860h7pkpl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissao
    ADD CONSTRAINT fk5u07riui9bg3m4ej860h7pkpl FOREIGN KEY (evento_id) REFERENCES public.evento(id);


--
-- Name: confronto fk6vm1ycaknbcsjna9aqrq8nm0g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.confronto
    ADD CONSTRAINT fk6vm1ycaknbcsjna9aqrq8nm0g FOREIGN KEY (submissao_casa_id) REFERENCES public.submissao(id);


--
-- Name: autora fk7b1nvxigmms9k1wmfw89lpsf7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.autora
    ADD CONSTRAINT fk7b1nvxigmms9k1wmfw89lpsf7 FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: submissao fkfigee0sstxvc7ai1qv98eklkk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissao
    ADD CONSTRAINT fkfigee0sstxvc7ai1qv98eklkk FOREIGN KEY (grupo_id) REFERENCES public.grupo_competicao(id);


--
-- Name: grupo_competicao fkgtj7xub8pwds0b02k9s8dqhpw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grupo_competicao
    ADD CONSTRAINT fkgtj7xub8pwds0b02k9s8dqhpw FOREIGN KEY (banca_id) REFERENCES public.usuario(id);


--
-- Name: confronto fkmt8eb0qrm5wwlywm6egke449l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.confronto
    ADD CONSTRAINT fkmt8eb0qrm5wwlywm6egke449l FOREIGN KEY (submissao_fora_id) REFERENCES public.submissao(id);


--
-- Name: voto_final fknjkq6pgsvqv2re5t52ntkb6pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voto_final
    ADD CONSTRAINT fknjkq6pgsvqv2re5t52ntkb6pr FOREIGN KEY (banca_id) REFERENCES public.usuario(id);


--
-- Name: voto_final fkqmt25lay1m3ch09hmlmabq0cf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voto_final
    ADD CONSTRAINT fkqmt25lay1m3ch09hmlmabq0cf FOREIGN KEY (submissao_id) REFERENCES public.submissao(id);


--
-- Name: aceite_termo fks6kxleypisswkqp1ukx6w5p4p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aceite_termo
    ADD CONSTRAINT fks6kxleypisswkqp1ukx6w5p4p FOREIGN KEY (submissao_id) REFERENCES public.submissao(id);


--
-- PostgreSQL database dump complete
--
